### ISSUE TITLE
NPE JukeAlertLogger.getSnitchList

### ISSUE THREAD

**Issue by erocs** [Civcraft/JukeAlert#14]
2015-02-01 19:28:03 [WARN] Exception in thread "Craft Scheduler Thread - 193"
2015-02-01 19:28:03 [WARN] org.apache.commons.lang.UnhandledException: Plugin JukeAlert v1.2.7 generated an exception while executing task 893268
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.mysql.jdbc.ResultSetImpl.buildIndexMapping(ResultSetImpl.java:750)
        at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1108)
        at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5616)
        at com.untamedears.JukeAlert.storage.JukeAlertLogger.getSnitchList(JukeAlertLogger.java:670)
        at com.untamedears.JukeAlert.tasks.GetSnitchListPlayerTask.run(GetSnitchListPlayerTask.java:28)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by rourke750** [comment]
maybe search through the mysql table and run this.  SELECT COUNT(*) FROM snitches WHERE snitch_group is null;

**Comment by erocs** [comment]
count == 0
