### ISSUE TITLE
Exception in thread "Craft Scheduler Thread - 364" 

### ISSUE THREAD

**Issue by ttk2** [Civcraft/JukeAlert#16]
2015-02-08 18:55:17 [WARN] Exception in thread "Craft Scheduler Thread - 364" 
2015-02-08 18:55:17 [WARN] org.apache.commons.lang.UnhandledException: Plugin JukeAlert v1.3.0 generated an exception while executing task 957049
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.mysql.jdbc.ResultSetImpl.buildIndexMapping(ResultSetImpl.java:750)
        at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1108)
        at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5616)
        at com.untamedears.JukeAlert.storage.JukeAlertLogger.getSnitchList(JukeAlertLogger.java:670)
        at com.untamedears.JukeAlert.tasks.GetSnitchListPlayerTask.run(GetSnitchListPlayerTask.java:28)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by spaceFountain** [comment]
[This](https://github.com/Civcraft/JukeAlert/blob/master/src/com/untamedears/JukeAlert/storage/JukeAlertLogger.java#L670) is where it seems to happen. Null group?

**Comment by ttk2** [comment]
we probably still have plenty of null entires in the db from the ebeans mess

**Comment by erocs** [comment]
There are no null snitch_group fields in the DB.

**Comment by rourke750** [comment]
Has this happened in a while?

**Comment by ttk2** [comment]
I have not seen it
