### ISSUE TITLE
2015-03-24 21:24:32 [ERROR] [JukeAlert] Could not get Snitch List using playername PLAYERNAME

### ISSUE THREAD

**Issue by ttk2** [Civcraft/JukeAlert#19]
2015-03-24 21:24:32 [ERROR] [JukeAlert] Could not get Snitch List using playername PLAYERNAME
java.sql.SQLException: Operation not allowed after ResultSet closed
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:794) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1105) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5616) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at com.untamedears.JukeAlert.storage.JukeAlertLogger.getSnitchList(JukeAlertLogger.java:704) [JukeAlert-1.3.0.jar:?]
        at com.untamedears.JukeAlert.tasks.GetSnitchListPlayerTask.run(GetSnitchListPlayerTask.java:28) [JukeAlert-1.3.0.jar:?]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_75]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_75]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]

**Comment by rourke750** [comment]
Which server is this.

**Comment by ttk2** [comment]
live.

**Comment by rourke750** [comment]
I'll try have something by tommorow.

**Comment by rourke750** [comment]
https://github.com/Civcraft/JukeAlert/commit/f4d5fd43007bcfa96916d7d03aa5e4bd29545755 @ttk2 ready for civtest

**Comment by ttk2** [comment]
should I be pulling from dev or master?

**Comment by rourke750** [comment]
Dev

**Comment by ttk2** [comment]
oneline.
